# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/maksim/Рабочий стол/Практика/programDB"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/maksim/Рабочий стол/Практика/programDB"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/maksim/Рабочий стол/Практика/programDB/CMakeFiles" "/home/maksim/Рабочий стол/Практика/programDB//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/maksim/Рабочий стол/Практика/programDB/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DatabaseManager

# Build rule for target.
DatabaseManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DatabaseManager
.PHONY : DatabaseManager

# fast build rule for target.
DatabaseManager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseManager.dir/build.make CMakeFiles/DatabaseManager.dir/build
.PHONY : DatabaseManager/fast

#=============================================================================
# Target rules for targets named UnitTests

# Build rule for target.
UnitTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnitTests
.PHONY : UnitTests

# fast build rule for target.
UnitTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/build
.PHONY : UnitTests/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseManager.dir/build.make CMakeFiles/DatabaseManager.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseManager.dir/build.make CMakeFiles/DatabaseManager.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseManager.dir/build.make CMakeFiles/DatabaseManager.dir/main.c.s
.PHONY : main.c.s

module.o: module.c.o
.PHONY : module.o

# target to build an object file
module.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseManager.dir/build.make CMakeFiles/DatabaseManager.dir/module.c.o
.PHONY : module.c.o

module.i: module.c.i
.PHONY : module.i

# target to preprocess a source file
module.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseManager.dir/build.make CMakeFiles/DatabaseManager.dir/module.c.i
.PHONY : module.c.i

module.s: module.c.s
.PHONY : module.s

# target to generate assembly for a file
module.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseManager.dir/build.make CMakeFiles/DatabaseManager.dir/module.c.s
.PHONY : module.c.s

test/test_1.o: test/test_1.c.o
.PHONY : test/test_1.o

# target to build an object file
test/test_1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/test/test_1.c.o
.PHONY : test/test_1.c.o

test/test_1.i: test/test_1.c.i
.PHONY : test/test_1.i

# target to preprocess a source file
test/test_1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/test/test_1.c.i
.PHONY : test/test_1.c.i

test/test_1.s: test/test_1.c.s
.PHONY : test/test_1.s

# target to generate assembly for a file
test/test_1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/test/test_1.c.s
.PHONY : test/test_1.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... DatabaseManager"
	@echo "... UnitTests"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... module.o"
	@echo "... module.i"
	@echo "... module.s"
	@echo "... test/test_1.o"
	@echo "... test/test_1.i"
	@echo "... test/test_1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

